name: Task
description: Technischer Task oder Sub-Issue
title: "Task: <Kurzbeschreibung>"
labels: ["task"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Beschreibung
      placeholder: Was genau soll getan werden?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Definition of Done
      value: |
        - [ ] Code implementiert
        - [ ] Unit Tests geschrieben
        - [ ] PR erstellt
        - [ ] CI grün
    validations:
      required: true
